### ISSUE TITLE
Build error with message "Multiple dex files define Lcom/google/..."

### ISSUE THREAD

**Issue by liberman08** [cranberrygame/cordova-plugin-ad-vungle#5]
Keep getting this error after I've added your plugin:

```
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/
internal/zzmu;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:45
4)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
```

It works fine with the iOS version but not with android. please help

**Comment by ahmetakin** [comment]
Hello @liberman08 ,
Try to add in **build.gradle** file this   `configurations {
    all*.exclude group: 'com.android.support', module: 'support-v4'
    all*.exclude group: 'com.google.android.gms', module: 'play-services'
}`

after `apply plugin: 'android'` line.

Thanks.

**Comment by Ziv-Barber** [comment]
To fix this issue you should verify that you are NOT including the all play services (check your build.gradle file).
